name: Build HEX from source
on: [push]
jobs:
  compileViaCmake:
    runs-on: ubuntu-latest
    container: lpodkalicki/avr-toolchain:avr-gcc-10.2.0
    steps:
      - run: gcc --version
      - run: cmake --version
      - run: avr-objcopy --version
      - run: avr-objdump --version
      - run: avr-strip --version