name: Build HEX from source
on: [push]
jobs:
  sniffVersions:
    name: Sniff versions
    runs-on: ubuntu-latest
    container: lpodkalicki/avr-toolchain:latest
    steps:
      - run: avr-gcc --version
      - run: avr-g++ --version
      - run: cmake --version
      - run: avr-objcopy --version
      - run: avr-objdump --version
      - run: avr-strip --version
      - run: ninja --version
  compileViaCmake:
    name: Compile via CMake
    runs-on: ubuntu-latest
    container: lpodkalicki/avr-toolchain:latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: |
          ls -la
          ls -la ..
          cmake -G Ninja -B ./build/
          cd build
          ls -la
          ninja